name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub (optional, only if you plan to push the image to Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build the Docker image
        run: docker build -t apache-server .

      # Step 4: Run the Docker container
      - name: Run the container
        run: docker run -d -p 8080:80 --name apache-container apache-server

      # Step 5: Verify the container status
      - name: Verify container status
        run: docker ps -a

      # Step 6: Use curl to check if the webpage is served
      - name: Check webpage
        run: curl http://localhost:8080
